version: "3.8"
services:
  node:
    image: node:lts-slim
    container_name: node
    working_dir: /home/node/app/
    command: bash -c "npm i && npm start"
    ports:
      - 3210:3210
    volumes:
      - /d/workspace/estudos/backend/nodejs/rest-api:/home/node/app
    networks:
      - "apirest"

networks:
  apirest:
    driver: "bridge"
